### ISSUE TITLE
New path for `libfishhook`

### ISSUE THREAD

**Issue by johanforssell** [rhdeck/react-native-fix-xcode-10#1]
Hello

I _just_ installed Xcode 10 (release version) and this little helper was very useful for getting the `glog`-issue fixed. It could however not fix the `libfishhook.a is missing` problem.

On my system (`"react-native": "^0.55.4"` and `XCode Version 10.0 (10A255)`) I found the file here:

```
⇢  cd my_rn_project
⇢  find . -name libfishhook.a 
./ios/build/Build/Products/Debug-iphonesimulator/libfishhook.a
./ios/build/Build/Products/Debug-iphoneos/libfishhook.a
```

I copied it manually and now I can build the damn project again.

**Comment by iamsee** [comment]
hah "the damn !!"

**Comment by rhdeck** [comment]
Committed fix to utilize the new relative path. I believe, though, that 0.57.0 with release XCode 10 obviates the need for this package entirely.
